export const ADD_DATAVUZIX = "ADD_DATAVUZIX";
export const DATAVUZIX_LOADING = "DATAVUZIX_LOADING";
export const DATAVUZIX_FALIED = "DATAVUZIX_FALIED";

export const ADD_INIT_MAPFILTER = "ADD_INIT_MAPFILTER";
export const MAPFILTER_LOADING = "MAPFILTER_LOADING";
export const MAPFILTER_FAILED = "MAPFILTER_FAILED";
export const EDIT_MAPFILTER = "EDIT_MAPFILTER";

export const ADD_MAPMARKERSDATA = "ADD_MAPMARKERSDATA";
export const MAPMARKERSDATA_LOADING = "MAPMARKERSDATA_LOADING";
export const MAPMARKERSDATA_FAILED = "MAPMARKERSDATA_FAILED";
export const EDIT_MAPMARKERSDATA = "EDIT_MAPMARKERSDATA";


export const INIT_INFOWINDOW = "INIT_INFOWINDOW";
export const INFOWINDOW_LOADING = "INFOWINDOW_LOADING";
export const INFOWINDOW_FAILED = "INFOWINDOW_FAILED";
export const EDIT_INFOWINDOW = "EDIT_INFOWINDOW";

export const ADD_ADDRESSVALUE = "ADD_ADDRESSVALUE";
export const ADDRESSVALUE_LOADING = "ADDRESSVALUE_LOADING";
export const ADDRESSVALUE_FAILED = "ADDRESSVALUE_FAILED";
export const EDIT_ADDRESSVALUE = "EDIT_ADDRESSVALUE";