export const ADD_DATAVUZIX = "ADD_DATAVUZIX";
export const DATAVUZIX_LOADING = "DATAVUZIX_LOADING";
export const DATAVUZIX_FALIED = "DATAVUZIX_FALIED";

export const ADD_INIT_MAPFILTER = "ADD_INIT_MAPFILTER";
export const MAPFILTER_LOADING = "MAPFILTER_LOADING";
export const MAPFILTER_FAILED = "MAPFILTER_FAILED";
export const EDIT_MAPFILTER = "EDIT_MAPFILTER";

export const ADD_SPEECHTEXT = "ADD_SPEECHTEXT";
export const SPEECHTEXT_LOADING = "SPEECHTEXT_LOADING";
export const SPEECHTEXT_FALIED = "SPEECHTEXT_FALIED";

export const INIT_MAP_DETAILS = "INIT_MAP_DETAILS";
export const ADD_MAPMARKERSDATA = "ADD_MAPMARKERSDATA";
export const MAPMARKERSDATA_LOADING = "MAPMARKERSDATA_LOADING";
export const MAPMARKERSDATA_FAILED = "MAPMARKERSDATA_FAILED";
export const EDIT_MAPMARKERSDATA = "EDIT_MAPMARKERSDATA";
export const ANIMATE_MARKER = "ANIMATE_MARKER";
export const LOAD_MAP = " LOAD_MAP";
export const DISPLAY_MARKER_DETAILS = "DISPLAY_MARKER_DETAILS";
export const CHANGE_MAP_CENTER = "CHANGE_MAP_CENTER";
export const CLOSEST_MARKER = "CLOSEST_MARKER"
export const MOST_RECENT_MARKER = "MOST_RECENT_MARKER";
export const SEARCH_AS_MAP_MOVES = "SEARCH_AS_MAP_MOVES";

export const INIT_INFOWINDOW = "INIT_INFOWINDOW";
export const INFOWINDOW_LOADING = "INFOWINDOW_LOADING";
export const INFOWINDOW_FAILED = "INFOWINDOW_FAILED";
export const EDIT_INFOWINDOW = "EDIT_INFOWINDOW";

export const ADD_ADDRESSVALUE = "ADD_ADDRESSVALUE";
export const ADDRESSVALUE_LOADING = "ADDRESSVALUE_LOADING";
export const ADDRESSVALUE_FAILED = "ADDRESSVALUE_FAILED";
export const EDIT_ADDRESSVALUE = "EDIT_ADDRESSVALUE";

export const ADD_VIDEODATA = "ADD_VIDEODATA";
export const VIDEODATA_LOADING = "VIDEODATA_LOADING";
export const VIDEODATA_FAILED = "VIDEODATA_FAILED";

export const INIT_FEEDBACK = "INIT_FEEDBACK";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const FEEDBACK_LOADING = "FEEDBACK_LOADING";
export const FEEDBACK_FAILED = "FEEDBACK_FAILED";